### ISSUE TITLE
when encountering a non-integer value, `napi_get_value_int32` raises an exception instead of truncating the number

### ISSUE THREAD

**Issue by mmomtchev** [toyobayashi/emnapi#103]
The original `napi_get_value_int32` truncates floating point numbers while the `emnapi` version raises an exception.

I think this applies to all integer handling in emnapi.

https://github.com/nodejs/node-addon-api/issues/578

**Comment by mmomtchev** [comment]
I think that this happens only with `emscripten`

**Comment by mmomtchev** [comment]
This seems to be an `emscripten` issue when using `ASSERTIONS=2`

https://github.com/emscripten-core/emscripten/issues/19655

**Comment by toyobayashi** [comment]
Thanks to your investigation, I'll take a look later

**Comment by mmomtchev** [comment]
There is an old JavaScript trick that is `~~value` (double not), it has the effect of truncating `value` without (almost) any performance impact, however it does not work for 64 bit values.
