### ISSUE TITLE
undefined symbol: `napi_get_last_error_info`

### ISSUE THREAD

**Issue by diegosogari** [toyobayashi/emnapi#107]
Hello there. Thanks for making this project available. I'm using it to port a C++ library.

Currently, I'm using node-gyp to build the bindings for this library, and I'm almost done. The issue is that the `napi_get_last_error_info` symbol is not being exported from `library_napi.js`, while it is present in [js_native_api.h](https://github.com/toyobayashi/emnapi/blob/main/packages/emnapi/include/js_native_api.h#L59). I'm not sure, but it might be because the corresponding function in [error.ts](https://github.com/toyobayashi/emnapi/blob/main/packages/emnapi/src/error.ts#L8) starts with an underscore.

For reference, this is the error message from the node-gyp build command:

    wasm-ld: error: ./Release/obj.target/binding/src/binding.o: undefined symbol: napi_get_last_error_info

**Comment by toyobayashi** [comment]
`napi_get_last_error_info` is in `js_native_api.c`. For node-gyp usage, you can take a look at this: https://github.com/toyobayashi/emnapi-node-gyp-test

**Comment by toyobayashi** [comment]
and I'm working on add node-gyp support in https://github.com/toyobayashi/emnapi/pull/106, you can use the `common.gypi` that is in the pr branch.

**Comment by diegosogari** [comment]
Thanks for the feedback! I was able to make it work by linking the `libemnapi-basic.a` library, which is provided in the emnapi package.
