### ISSUE TITLE
Initialization order regression

### ISSUE THREAD

**Issue by RReverser** [toyobayashi/emnapi#15]
We yesterday spent half of the day chasing down a weird new bug in a large project, which ended up narrowing down to a regression in emnapi. Git bisect ended up pointing to aa2af0813e84954b78d443f40d8b1927f879a906.

Basically, that commit somewhat changed the ordering of init.

For background, any functions marked by `__attribute__((constructor))` in C/C++ end up added to a special `__wasm_call_ctors` function and Emscripten adds them to the init array via `addOnInit`.

`addOnInit` runs init functions in the reverse order, so `__wasm_call_ctors` - which is added last - is always expected to be invoked first.

That was true with emnapi before, but after the change in that commit emnapi's initialization invokes `addOnInit` later in the process, which means - due to reverse order - the callback will now be actually invoked first, invoking the NAPI module init before `__wasm_call_ctors`, and so before the C/C++ is actually ready.

I've added a failing regression test in https://github.com/toyobayashi/emnapi/pull/14 to demonstrate the behaviour, but I'll leave the fix to you as I'm not as closely familiar with the codebase.

**Comment by toyobayashi** [comment]
> I've added a failing regression test in #14

Thank you. I will take a look at this weekend.

**Comment by RReverser** [comment]
One thing that is still failing in my case is compilation with `-sWASM_ASYNC_COMPILATION=0`, which, in my case, is important for Node.js build to have synchronous API compatible with native addon.

 I suspect the reason is the same https://github.com/toyobayashi/emnapi/commit/aa2af0813e84954b78d443f40d8b1927f879a906 commit that made initialization asynchronous.

**Comment by toyobayashi** [comment]
My intention was to allow `@tybys/emnapi-runtime` can be imported automatically through dynamic import. Recently I've been thinking about how to simplify the initialization process, like this?

```js
Module.emnapi = {
  context: emnapi.createContext(),
  onInit (err, exports) {
    // if no error
    // Module.emnapi.exports === exports
  }
}
```

this make initialization no longer need to be asynchronous, and all options related to emnapi are in `emnapi` property, but need user always import `@tybys/emnapi-runtime` and reuse context themselves.

**Comment by RReverser** [comment]
> and reuse context themselves

In which case the context can / should be reused between modules? It's a bit unclear from docs. As in, why not just create it automatically per-Module?

> Recently I've been thinking about how to simplify the initialization process, like this?

Since module initialization itself doesn't technically need to run during the `__ATINIT__` phase, maybe export a factory instead? The factory itself could be synchronous and wouldn't need a callback, and then the user can choose when and how they want to init it, both synchronously and asynchronously, so the call itself would be just:

```js
let exports = Module.initEmnapi(emnapi.createContext());
```

**Comment by toyobayashi** [comment]
> In which case the context can / should be reused between modules?

Every context owns isolated `napi_env` / `napi_value` / `napi_handle_scope` / `napi_ref` / `napi_deferred` ...

Though I have not tested enough, I believe it is better to always reuse context between `Module`s, especially passing object across different emnapi Module.

In previous version of emnapi, `Handle` and JS object is a one-to-one relationship, and `Handle` had a ref array recorded all its `Reference`, if `ModuleA` and `ModuleB` use different context, `ModuleA.emnapiExports.foo()` call `ModuleB.emnapiExports.bar` internally and pass objects, then `bar` create references with finalizer to the object those from `ModuleA`, I'm not sure if there are bugs. Currently `Handle` and JS object is no longer one-to-one relationship, but both handle scope and callback info are linked list, I'm also not sure if there are bugs call binding functions across Modules.

> module initialization itself doesn't technically need to run during the __ATINIT__ phase

My original design was that emnapi initialization should be done before `onRuntimeInitialized` so that user can access exports in  `onRuntimeInitialized`, so `napi_register_wasm_v1` should be called in __ATINIT__ phase.

```js
Module.onRuntimeInitialized = function () {
  let exports = Module.initEmnapi(emnapi.createContext());
}
```

In this way, the order is reversed

**Comment by RReverser** [comment]
> In this way, the order is reversed

Yes, it's reversed, but it also becomes a bit more flexible. Among other things, it allows to load & init Module & runtime in parallel, and then connect them together.

Also, with ES6 module output (which, arguably, should become the default in Emscripten at some point) `onRuntimeInitialized` isn't idiomatic anymore, instead relying on promises. Combined with factory API, the code would look pretty natural and would load runtime & the module itself in parallel:

```js
import initModule from './my_napi_module.mjs';
import { createContext } from '@tybys/emnapi-runtime';

export default createContext(await initModule());
```

whereas with proposed approach above it would look a bit inverted, for the lack of better word:

```js
import initModule from './my_napi_module.mjs';
import { createContext } from '@tybys/emnapi-runtime';

let exports;
await initModule({
  context: createContext(),
  onInit(err, _exports) {
    if (err) throw err;
    exports = _exports;
  }
});

export default exports;
```

**Comment by toyobayashi** [comment]
Thank you. I see, I will find some time work on this.

**Comment by RReverser** [comment]
Sorry, it was late last night and I made couple of mistakes in my code examples; updated now.

**Comment by toyobayashi** [comment]
That's ok. I knew what you mean. Created #22
