### ISSUE TITLE
node-gyp support?

### ISSUE THREAD

**Issue by toyobayashi** [toyobayashi/emnapi#23]
It would be nice if node-gyp can work with emnapi on win/linux/mac.

**Comment by RReverser** [comment]
Yup, I'm planning to upstream the mentioned common.gypi that I intentionally kept separate from sharp-specific variables.

**Comment by RReverser** [comment]
It's because it still needs a bit more work for an actual PR, otherwise I'd already upstream it :P

**Comment by toyobayashi** [comment]
I tried `node-gyp ... -- -f make` on Windows, and it generated wrong path seperator `\` instead of `/` in makefile, then `emmake.bat make` in mingw64 bash failed. On macOS, it generated arm64 related compile flags, which is complained by emcc. Out of curiosity, could you give me some hint how to workaround such gyp default behavior on different OS? Is it require upstream gyp code change, or all these problem can be solved by configuration file and some command line flags?

**Comment by toyobayashi** [comment]
Oh sorry, I don't mean to rush you. Looking forward to your PR in patient, not worry

**Comment by RReverser** [comment]
No problem, just saying it's been messy and don't know when I'll get around to this. If you want, I can commit just the common.gypi for now so that at least Linux users would have a way forward, and we can figure out the other OS later.

**Comment by toyobayashi** [comment]
depends on your opinion. emnapi has few users, perhaps you are the first one. I don't mind to wait :)

**Comment by mmomtchev** [comment]
I am also interested in this feature and I am ready to contribute if anything is still missing. FYI, I am the author of SWIG Node-API and I planning to use `emnapi` to support transparent rebuilding for browser targets. I plan to to treat `wasm` as a separate, fourth `node-gyp` platform.

**Comment by toyobayashi** [comment]
@mmomtchev Thank you so much! I still don't know how to make node-gyp works for all platforms. I created a reproduce repo here: https://github.com/toyobayashi/emnapi-node-gyp-test

**Comment by mmomtchev** [comment]
Thanks, will give it a try. This project is a wonderful idea, it opens many new doors. I am also the author/maintainer of a number of Node.js addons.

**Comment by toyobayashi** [comment]
Good news! Found ways to build successfully on Windows and macOS.

https://github.com/nodejs/node-gyp/issues/2823#issuecomment-1892254153.

I have pushed to [emnapi-node-gyp-test](https://github.com/toyobayashi/emnapi-node-gyp-test).

**Comment by mmomtchev** [comment]
One of the ugliest parts of the `node-gyp` build is that `node-gyp` insists on using relative filenames that recreate the source tree in `build` - which means that if you are referencing source files out of this tree - especially if they come from `/usr/lib/node_modules` or any other global installation - then your `.o` files tend to pop up in rather unexpected places - such as few directories above the build directory.

**Comment by toyobayashi** [comment]
`common.gypi` is added in https://github.com/toyobayashi/emnapi/releases/tag/v1.0.0.

upstream changes required:

- https://github.com/nodejs/gyp-next/pull/222
- https://github.com/nodejs/node-gyp/pull/2974

test with patches: https://github.com/toyobayashi/emnapi-node-gyp-test/actions

I think we can close this issue now since works in this repo has been done. Open issues at any time if have more specific problems.

**Comment by RReverser** [comment]
Awesome! I suspected that it would require upstream fixes but didn't want to dig into node-gyp itself 😅 Thanks for doing this (and for preserving the author notice)!
