### ISSUE TITLE
AsyncWorkers prevent Node.js from exiting

### ISSUE THREAD

**Issue by toyobayashi** [toyobayashi/emnapi#25]
lovell/sharp#3522

https://github.com/lovell/sharp/pull/3522/files#diff-f1d20c9f37b79bd0729e7379d212de61e425488d7ceb987ed964326f874d7c43R44-R66

**Comment by RReverser** [comment]
Oh nice, I thought I'd eventually implement this myself but cool that you already did 😅

I think it's still better at some point to implement as much as possible upstream in Emscripten though - in particular, there is no reason not to add the refcounter to `emscripten_keepalive_runtime_{push,pop}` which you already used.

**Comment by toyobayashi** [comment]
Agree with you. But I'm not familiar with how to contribute emscripten codebase, and it may be not easy to pull some dependencies due to the network environment limitation in China mainland. Could you help take this to emscripten?

In addition, is there a better way than using `setInterval`?

**Comment by RReverser** [comment]
> and it may be not easy to pull some dependencies

I don't think it uses any special dependencies outside of what emsdk has (Python and Node.js + some modules). Not sure if any of those modules are blocked in China, but worth a try. But yeah, I can try and can help myself too.

> In addition, is there a better way than using `setInterval`?

Oh... you're using setInterval? Where? That definitely shouldn't be necessary.

**Comment by toyobayashi** [comment]
https://github.com/toyobayashi/emnapi/blob/adbc3d01a09999b7dab195fc25793d48a095ef35/packages/runtime/src/Context.ts#L80-L99

I didn't think of any other way at the time. All the emnapi async worker threads should be unreffed, but there must be a strong ref to prevent nodejs from exiting the event loop.

**Comment by RReverser** [comment]
Yeah I was thinking on it before for the mentioned contribution, and I thought I'd go with `MessageChannel` instead. `MessagePort` is probably the most lightweight way to `.ref()`/`.unref()` something without ever accidentally triggering the handler or having to subscribe to the timer.

That is, just do `refHandle = new MessageChannel().port1` and use that for all `.ref()`/`.unref()` operations.

**Comment by toyobayashi** [comment]
Thanks, learned from you again
