### ISSUE TITLE
Regression between 0.20.0..0.25.1

### ISSUE THREAD

**Issue by RReverser** [toyobayashi/emnapi#30]
Sorry for the vague description, but not sure how to narrow it down further yet. I tried to upgrade the sharp PR to newer emnapi, and got weird test failures. In the end I could narrow it down to somewhere between 0.20.0 which I used in the PR and 0.25.1 which is the first version with WASM_ASYNC_COMPILATION-compatible fix for https://github.com/toyobayashi/emnapi/issues/15.

The failures I'm seeing seem to indicate some global state sharing isssue, either in Buffer allocation / copying, or maybe in error state handling. I can't think of any good explanation without digging much deeper.

Check out this commit for the repro: https://github.com/RReverser/sharp-fork/commit/295d47848321da018ffedb3f07c65ab53a766c66

Example:

```
> npx --arch=wasm32 mocha -g 'Grayscale to RGBA, file'


  Image channel insertion
    ✔ Grayscale to RGBA, file
    1) Grayscale to RGBA, files, two arrays


  1 passing (410ms)
  1 failing

  1) Image channel insertion
       Grayscale to RGBA, files, two arrays:
     Uncaught Error: Input buffer contains unsupported image format
      at _napi_create_error (build/Release/sharp-emscripten-wasm32.node.js:5620:14)
      at Napi::Error::New(napi_env__*, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>> const&) (wasm://wasm/02b27b26:wasm-function[396]:0x212f1)
      at invoke_viii (build/Release/sharp-emscripten-wasm32.node.js:7691:27)
      at PipelineWorker::OnOK() (wasm://wasm/02b27b26:wasm-function[481]:0x50e86)
      at Napi::AsyncWorker::OnWorkComplete(Napi::Env, napi_status)::'lambda'()::operator()() const (wasm://wasm/02b27b26:wasm-function[380]:0x1ab29)
      ...
```

fails but running same tests individually works fine:

```
> npx --arch=wasm32 mocha -g 'Grayscale to RGBA, file$'


  Image channel insertion
    ✔ Grayscale to RGBA, file


  1 passing (327ms)

> npx --arch=wasm32 mocha -g 'Grayscale to RGBA, files, two arrays'


  Image channel insertion
    ✔ Grayscale to RGBA, files, two arrays


  1 passing (334ms)
```

Same as above happens in few other tests, and finally one test has a new timeout problem:

```
> npx --arch=wasm32 mocha -g 'Stream in, finish event fires before metadata is requested'


  Image metadata
    1) Stream in, finish event fires before metadata is requested


  0 passing (30s)
  1 failing

  1) Image metadata
       Stream in, finish event fires before metadata is requested:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/rreverser/sharp/test/unit/metadata.js)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)
```

None of these issues were reproducible with v0.20.0, but seem to be reproducible with every version from at least v0.25.1 to latest. Maybe I just refactored to `emnapiInit` incorrectly but can't seem to figure out what went wrong, and the errors seem suspicious so I'm inclined to think it's some change in the emnapi itself.

**Comment by toyobayashi** [comment]
I'll take a look tonight (morning in your timezone?) then give feedback here

**Comment by toyobayashi** [comment]
Could you narrow down from which emnapi version among 0.20.0 - 0.25.1 this issue occurs in the `node-wasm-squash` branch code? I tried to rebuild the project in `node-wasm-squash` branch with emnapi v0.24.0, but I can not get the dependencies with the terrible network...

**Comment by toyobayashi** [comment]
I guess following version changes may cause this

- 0.22.0 (runtime big refactor for better performance)
- 0.24.0 (new buffer API, try `emnapi_create_memory_view` [here](https://github.com/RReverser/sharp-fork/commit/295d47848321da018ffedb3f07c65ab53a766c66#diff-53a01d31aa585021f8f316c6613dadef86bf1f9ac2070d52daa68adbefbb6ef4L87) ?)

I can't verify my thoughts since I can't do a rebuild. Current version emnapi code changes a lot since 0.20.0, at least figure out from what exact version test fails may help more.

**Comment by RReverser** [comment]
> Could you narrow down from which emnapi version among 0.20.0 - 0.25.1 this issue occurs in

I tried but couldn't because of

> which is the first version with WASM_ASYNC_COMPILATION-compatible fix for #15.

Without that I couldn't run any tests temporarily :(

**Comment by RReverser** [comment]
> but I can not get the dependencies with the terrible network...

Have you tried Github Codespaces? Maybe it's easier to work on it remotely rather than fetch everything locally.

**Comment by toyobayashi** [comment]
> Have you tried Github Codespaces?

Tried just now, still couldn't rebuild due to error `(received SIGKILL (-9))` during linking.

```
  LINK(target) Release/sharp-emscripten-wasm32.node.js
em++: warning: USE_PTHREADS + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271 [-Wpthreads-mem-growth]
em++: error: '/emsdk/upstream/bin/wasm-ld -o Release/sharp-emscripten-wasm32.node.wasm ./Release/obj.target/sharp-emscripten-wasm32/node_modules/@tybys/emnapi/src/emnapi.o ./Release/obj.target/sharp-emscripten-wasm32/node_modules/@tybys/emnapi/src/uv/uv-common.o ./Release/obj.target/sharp-emscripten-wasm32/node_modules/@tybys/emnapi/src/uv/threadpool.o ./Release/obj.target/sharp-emscripten-wasm32/node_modules/@tybys/emnapi/src/uv/unix/loop.o ./Release/obj.target/sharp-emscripten-wasm32/node_modules/@tybys/emnapi/src/uv/unix/thread.o ./Release/obj.target/sharp-emscripten-wasm32/node_modules/@tybys/emnapi/src/uv/unix/async.o ./Release/obj.target/sharp-emscripten-wasm32/node_modules/@tybys/emnapi/src/uv/unix/core.o ./Release/obj.target/sharp-emscripten-wasm32/src/common.o ./Release/obj.target/sharp-emscripten-wasm32/src/metadata.o ./Release/obj.target/sharp-emscripten-wasm32/src/stats.o ./Release/obj.target/sharp-emscripten-wasm32/src/operations.o ./Release/obj.target/sharp-emscripten-wasm32/src/pipeline.o ./Release/obj.target/sharp-emscripten-wasm32/src/utilities.o ./Release/obj.target/sharp-emscripten-wasm32/src/sharp.o -L/src/build/target/lib /src/build/target/lib/libvips-cpp.a /src/build/target/lib/libvips.a /src/build/target/lib/libjpeg.a /src/build/target/lib/libz.a /src/build/target/lib/libwebp.a /src/build/target/lib/libaom.a /src/build/target/lib/libgio-2.0.a /src/build/target/lib/libgmodule-2.0.a /src/build/target/lib/libgobject-2.0.a /src/build/target/lib/libglib-2.0.a /src/build/target/lib/libffi.a /src/build/target/lib/libexpat.a /src/build/target/lib/libimagequant.a /src/build/target/lib/libcgif.a /src/build/target/lib/libexif.a /src/build/target/lib/libspng.a /src/build/target/lib/libwebpmux.a /src/build/target/lib/libwebpdemux.a /src/build/target/lib/libtiff.a /src/build/target/lib/liblcms2.a /src/build/target/lib/libheif.a -L/src/build/emcache/sysroot/lib/wasm32-emscripten /src/build/emcache/sysroot/lib/wasm32-emscripten/crtbegin.o -lstubs -lnoexit -lc-mt -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt -lc++abi-mt -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmp8xh14m3z.undefined --import-memory --shared-memory --export-if-defined=vips_shutdown --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=_emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=emscripten_dispatch_to_thread_ --export=_emscripten_thread_free_data --export=emscripten_main_browser_thread_id --export=emscripten_main_thread_process_queued_calls --export=emscripten_run_in_main_runtime_thread_js --export=emscripten_stack_set_limits --export=getTempRet0 --export=setTempRet0 --export=__cxa_is_pointer_type --export=__cxa_can_catch --export=setThrew --export=__cxa_free_exception --export=malloc --export=free --export=saveSetjmp --export=emscripten_builtin_memalign --export=ntohs --export=htons --export=htonl --export=__dl_seterr --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=1024' failed (received SIGKILL (-9))
make: *** [sharp-emscripten-wasm32.target.mk:234: Release/sharp-emscripten-wasm32.node.js] Error 1
make: Leaving directory '/sharp-src/build'
```

I guess it is bug here

https://github.com/RReverser/sharp-fork/blob/295d47848321da018ffedb3f07c65ab53a766c66/src/common.cc#L99-L101

Maybe something wrong happened to the requested `data` of `napi_get_typedarray_info` in `TypedArrayOf<T>::TypedArrayOf(napi_env, napi_value)`, not sure. I don't know how to reproduce :(

**Comment by toyobayashi** [comment]
`napi_get_typedarray_info` behavior change in [0.23.0](https://github.com/toyobayashi/emnapi/releases/tag/v0.23.0)

**Comment by toyobayashi** [comment]
Before 0.23.0 the `data` is always `NULL`, after 0.23.0 it is memory copy, perhaps somewhere needs sync memory between JS and wasm

**Comment by RReverser** [comment]
> I guess it is bug here
> 
> [RReverser/sharp-fork@`295d478`/src/common.cc#L99-L101](https://github.com/RReverser/sharp-fork/blob/295d47848321da018ffedb3f07c65ab53a766c66/src/common.cc#L99-L101)

Hmm it reads data only once though, and doesn't care about changes in the input. Why would it need manual synchronisation?

**Comment by toyobayashi** [comment]
So it is strange, but I can't find anything else suspicious

```
toBuffer
_pipeline
sharp.pipeline
baton->joinChannelIn.push_back(
        sharp::CreateInputDescriptor(joinChannelArray.Get(i).As<Napi::Object>()));
```

**Comment by toyobayashi** [comment]
I search the error message, it's only here

![image](https://user-images.githubusercontent.com/23353576/218144636-11f18d2d-878d-435e-9f8e-e22a89afa524.png)

then I search `buffer =`, it's only here

![image](https://user-images.githubusercontent.com/23353576/218144960-fb05c024-0353-47f5-9fc6-a4adc115535c.png)

**Comment by RReverser** [comment]
Yes; the thing is, that error message doesn't show up in individual tests as you can see in the beginning, so it does look like some internal memory corruption when tests are running one after another, but not something in sharp code as it doesn't reproduce either natively or in old version of emnapi.

Maybe some Buffer backing memory ends up accidentally reused?

**Comment by toyobayashi** [comment]
Thank you. It's a bit late now, I'll find time tomorrow to continue taking a look. It would be nice if you could help find a minimal reproduce case, so that we can verify whether really fix it before publish a new version.

**Comment by RReverser** [comment]
> It would be nice if you could help find a minimal reproduce case

Yeah I understand, just couldn't do that yet and had to switch to a different project for now. I'll try to look again when I have time, just wanted to at least submit issue for tracking for now.

**Comment by toyobayashi** [comment]
Probably here, after 0.23.0 no longer record typedarray in WeakMap, check its `.buffer` instead.

https://github.com/toyobayashi/emnapi/blob/75d937d58fff5e5d4961dc5bfcc93a46f433f1c2/packages/emnapi/src/memory.ts#L129

Before 0.23.0, typedarrays are in a seperate WeakMap.

https://github.com/toyobayashi/emnapi/blob/182856c15167a930161f0dbad5895d8a175f1016/packages/emnapi/src/util.ts#L87-L98

The problem is, Node.js buffer will reuse buffer pool when allocate a small size buffer. 

https://github.com/nodejs/node/blob/be4921474671fb15f0e62adfe2f37253d07eca02/lib/buffer.js#L398-L411

This means some small Buffer's `buffer` is the ArrayBuffer of the buffer pool, offset is mismatched with the original buffer and it is reused, then cause memory corruption during small buffer allocation somewhere.

You may not believe it, the above is what I suddenly thought of in a dream last night. Further verification is needed

**Comment by toyobayashi** [comment]
More specifically, if two small buffers share the same buffer pool, the requested `data` of `napi_get_typedarray_info` (or similar API) may be wrong!

**Comment by toyobayashi** [comment]
Now I'm pretty sure it is the buffer pool reusing causing the problem.

I added `Buffer.poolSize = 0` at top of `sharp-emscripten-wasm32.node.js`, then all tests succeed!

**Comment by toyobayashi** [comment]
But unfortunately I'm still not sure the source code position where is actually trigger overwriting the shared buffer pool. I manually modified the generated `sharp-emscripten-wasm32.node.js` with the old `$getViewPointer` logic, it works indeed.
